version: '2'

services:
  mysqldb:
    image: mysql:5.7
    networks:
      - network
    environment:
      MYSQL_DATABASE: 'achatdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"

  devops_backend:
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true
    networks:
      - network
    image: devops_back_project
networks:
  network: